### ISSUE TITLE
Test merchant alias operations and async service

### ISSUE THREAD

**Issue by pnmcosta** [pnmcosta/PMC.MBWay.Net#2]

**Comment by brunobola** [comment]
Bom dia Pedro, antes de mais obrigado pela ajuda.
Precisava que me desses mais umas dicas da Tua API, estou eu a preparar uma demonstração no ambiente de testes da SIBS, no entanto após falar com a SIBS, mas eles referiram que na resposta assíncrona não recebem o OK do meu Webservice, sabes o que pode ser?

De facto um print do WcfTestClient fica com o resultado assim:
Sabes o que pode ser ?

**Comment by pnmcosta** [comment]
Bom dia Bruno,

Por favor, crie um novo issue, visite https://github.com/pnmcosta/PMC.MBWay.Net/issues/new este é referente a outro assunto em nada relacionado com o seu problema.

Obrigado,
P.

**Comment by brunobola** [comment]
Já criei outro e apaguei o incidente anterior.

Assim que possas diz-me alguma dica: https://github.com/pnmcosta/PMC.MBWay.Net/issues/3

 

 

Melhores Cumprimentos,

Best regards,

 

Bruno Marques

(+351 916 311 580 <tel:%28%2B351%20916%20311%20580> )

 



 

Antes de imprimir este e-mail, pense bem se é realmente necessário fazê-lo. 

Before printing this email, think whether it is really necessary to do so.

 

De: Pedro Costa [mailto:notifications@github.com] 
Enviada: 28 de junho de 2016 11:30
Para: pnmcosta/PMC.MBWay.Net <PMC.MBWay.Net@noreply.github.com>
Cc: brunobola <brunobola@gmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [pnmcosta/PMC.MBWay.Net] Test merchant alias operations and async service (#2)

 

Bom dia Bruno,

Por favor, crie um novo issue, visite https://github.com/pnmcosta/PMC.MBWay.Net/issues/new este é referente a outro assunto em nada relacionado com o seu problema.

Obrigado,
P.
