### ISSUE TITLE
Problema ao Receber Resposta Assyncrona

### ISSUE THREAD

**Issue by brunobola** [pnmcosta/PMC.MBWay.Net#3]
Bom dia Pedro, antes de mais obrigado pela ajuda.
Precisava que me desses mais umas dicas da Tua API, estou eu a preparar uma demonstração no ambiente de testes da SIBS, no entanto após falar com a SIBS, mas eles referiram que na resposta assíncrona não recebem o OK do meu Webservice, sabes o que pode ser?

De facto um print do WcfTestClient fica com o resultado assim:
Sabes o que pode ser ?

**Comment by pnmcosta** [comment]
Bom dia Bruno,

Efectuei um teste com o código fonte da API, e o que vê na imagem é o esperado, visualmente aparece vazio:
![mbway_im1](https://cloud.githubusercontent.com/assets/550684/16412644/48051dfa-3d25-11e6-8675-a3733a2fa6d0.JPG)

Contudo, na sua representação XML, contem um "valor", de um objecto do tipo financialOperationResultResponse vazio:
![mbway_im2](https://cloud.githubusercontent.com/assets/550684/16412662/5f6ea042-3d25-11e6-903e-b2b4a96112ea.JPG)

Deduzo que o não OK da SIBS poderá ser de por exemplo não conseguirem acesso ao service, contudo por favor confirme que: 

- o webservice implementa `MBWayAsyncServiceBase`
- o webservice tem os bindings como em https://github.com/pnmcosta/PMC.MBWay.Net/blob/master/PMC.MBWay.Net.TestSite/Web.config (contudo poderá ter que fazer pequenas modificações dependendo do seu ambiente)
- o SSL é valido
- que ao criar o `MBWayClient` para a transacção inicial a setting `AsyncServiceEndpoint` está bem definida, este é o endereço que o MBWAY utiliza para chamar o website

Se tudo estiver em order, terá que entrar em contacto com a SIBS novamente de forma a poder efectuar nova ronda de testes.

Durante os testes desta API tivemos alguns problemas semelhantes, mas foi com a configuração dos cartões. 

Tanto esta API como, o modulo Kentico que desenvolvemos com base nela, ver http://pmc.digital/mbway, foram testados com sucesso pela SIBS na semana passada.

Contudo, se necessitar de mais alguma ajuda, não hesite em perguntar.

Cumprimentos,
P.

**Comment by brunobola** [comment]
OK, o SSL é válido, basicamente tenho o seguinte cenário, tenho um servidor de acesso livre em que apenas fiz rebuild do teu código do projeto PMC.MBWay.Net.TestSite e coloquei lá.
Depois tenho o projeto de teste winforms na minha máquina em que tenho isto:
...
        private MBWayClient client;
        protected requestFinancialOperationResult currentResult;
...
private void TestePagamento()
        {
            //TestAlias => Telemóvel de teste
            int valor = 1000;
            var aliasCompra = "351#912076012";

            //Processo de Autorização
            var transacaoDeCompra = GetRequest(AliasTypes.CELLPHONE, aliasCompra);

            var amount = valor;
            var operationId = MBWayClient.GetUniqID();
            var currencyCode = CurrencyCodes.EURO_TWO_DECIMALS;

            transacaoDeCompra.financialOperation = new financialOperation
            {
                amount = valor,
                currencyCode = currencyCode,
                merchantOprId = operationId,
                operationTypeCode = FinancialOperationTypes.PURCHASE_AUTHORIZATION
            };

            var resultadoAutorizacao = this.GetClient().RequestFinancialOperation(transacaoDeCompra);
            if (resultadoAutorizacao == null)
            {
                XtraMessageBox.Show(this, "Não foi possivel efetuar o pedido de autorização, tente Novamente.", "Informação", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            else
            {
                if (resultadoAutorizacao.IsValid)
                {
                    if (!resultadoAutorizacao.amountSpecified)
                    {
                        //Faz processo de anulação de operação financeira
                        XtraMessageBox.Show(this, "Não foi existe valor na trasação a efetuatar [" + resultadoAutorizacao.statusCode + "], tente Novamente.", "Informação", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        return;
                    }
                    else
                    {
                        //Continua Processo!!!
                    }
                }
                else
                {
                    XtraMessageBox.Show(this, "Não foi possivel efetuar o pedido de autorização [" + resultadoAutorizacao.statusCode + "], tente Novamente.", "Informação", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }
            }

            //Assert.IsNotNull(currentResult);
            //Assert.IsTrue(currentResult.IsValid);

            ApprovalSleep(); // allow for aproval in app and async callback

            var newOperationId = MBWayClient.GetUniqID();
            transacaoDeCompra.financialOperation = new financialOperation
            {
                amount = resultadoAutorizacao.amount,
                currencyCode = resultadoAutorizacao.currencyCode,
                merchantOprId = newOperationId,
                operationTypeCode = FinancialOperationTypes.PURCHASE_AFTER_AUTHORIZATION
            };

            if (resultadoAutorizacao.statusCode == ReturnStatusCodes.SUCCESS)
            {
                var newOperationId2 = MBWayClient.GetUniqID();
                transacaoDeCompra.financialOperation = new financialOperation
                {
                    amount = resultadoAutorizacao.amount,
                    currencyCode = resultadoAutorizacao.currencyCode,
                    merchantOprId = newOperationId,
                    operationTypeCode = FinancialOperationTypes.PURCHASE_RETURN
                };

                toastNotificationsManager1.ShowNotification(toastNotificationsManager1.Notifications[0]);
                //XtraMessageBox.Show(this, "Pagamento realizado com sucesso.", "Informação", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            //var resultado3 = this.GetClient().RequestFinancialOperation(request);

            //Assert.IsTrue(resultado3.IsValid);
            //Assert.AreEqual(currentResult.amount, resultado3.amount);
            //Assert.AreEqual(newOperationId, resultado3.merchantOperationID);
            //Assert.AreEqual(currentResult.currencyCode, resultado3.currencyCode);
            //Assert.IsNotNull(resultado3.timestamp);

            //currentResult = resultado3;
        }

O Ficheiro APP.Config tem isto:
  <appSettings>
    
    <add key="CERTIFICATE_THUMBPRINT" value="‎5887101e4e7f869768392e536842e9aa9d4791f9" />
    
    <add key="CERTIFICATE_PATH" value="E:\Implementacoes\MB_WAY\certificado_mbway.pfx" />
    <add key="CERTIFICATE_PASS" value="TESTE" />
    <add key="MERCHANT_IP" value="93.108.238.10" />
    <add key="MERCHANT_POSID" value="27882" />
    
    <add key="ASYNC_SERVICE_ENDPOINT" value="https://ws.trigenius.com/mbway/MBWayAsyncService.svc" />
    
    <add key="TEST_APPROVAL_SLEEP" value="30000" />
    
    <add key="TEST_ALIAS" value="351#912076012" />
  </appSettings>

O que faltará fazer :(

**Comment by brunobola** [comment]
<add key="CERTIFICATE_THUMBPRINT" value="‎5887101e4e7f869768392e536842e9aa9d4791f9" />
    <add key="CERTIFICATE_PATH" value="E:\Implementacoes\MB_WAY\certificado_mbway.pfx" />
    <add key="CERTIFICATE_PASS" value="TESTE />
    <add key="MERCHANT_IP" value="93.108.238.10" />
    <add key="MERCHANT_POSID" value="27882" />
    <add key="ASYNC_SERVICE_ENDPOINT" value="https://ws.trigenius.com/mbway/MBWayAsyncService.svc" />
    <add key="TEST_APPROVAL_SLEEP" value="30000" />
    <add key="TEST_ALIAS" value="351#912076012" />

**Comment by brunobola** [comment]
O que faltará fazer :(

**Comment by pnmcosta** [comment]
Boas Bruno,

Terá que seguir este exemplo, para criar novas transações:

```
    using PMC.MBWay.Net;

    // Create client with prefered certificate method
    MBWayClient client = new MBWayClient(new MBWayConfig
    {
        // certificate's SHA1 thumbprint from the Local Computer\Personal\Certificates store
        CertificateThumbprint = "f4eaa0362ccec7a03f76786052037483c50fde36",

        // or use a password protected pfx file
        //CertificatePass = "Your!CertificatePassword123!",
        //CertificatePath = "c:\\path\\to\\cerficiate.pfx",

        MerchantIP = "Your.Ip.Address",
        MerchantPOSID = "YourPOSId",
        AsyncServiceEndpoint = "https://path/to/asyncservice.svc"
    });

    var request = new requestFinancialOperationRequest
    {
        alias = new alias
        {
            aliasName = "351#911231231",
            aliasTypeCde = AliasTypes.CELLPHONE
        },

        merchant = new merchant
        {
            iPAddress = client.CurrentConfig.MerchantIP,
            posId = client.CurrentConfig.MerchantPOSID
        },

        messageProperties = new messageProperties
        {
            apiVersion = "1",
            channel = MessageChannelTypes.WEB,
            channelTypeCode = "VPOS",
            networkCode = "MULTIB",
            serviceType = "01",
        },

        aditionalData = "TEST CLIENT",

        financialOperation = new financialOperation
        {
            amount = 70, //0.70€
            currencyCode = CurrencyCodes.EURO_TWO_DECIMALS,
            merchantOprId = MBWayClient.GetUniqID(),
            operationTypeCode = FinancialOperationTypes.PURCHASE
        }
    };

    var result = client.RequestFinancialOperation(request);
```

Olhando brevemente pelo codigo que partilhou, parece-me que está a usar pedaços de codígo do unit test, e sinceramente, não o consigo entender.

Usando o exemplo simplificado acima, continua a ter o mesmo problema?

Obrigado,
P.

**Comment by brunobola** [comment]
Como estava em ambiente de testes, tive que alterar para sandbox, mas como faço usando o exemplo em cima para apanhas os rejeitados? É que mesmo usando um tempo de espera:

 Thread.Sleep(int.Parse(ConfigurationManager.AppSettings["TEST_APPROVAL_SLEEP"]));

Recebo sempre "000", o que pode ser ?
Obrigado pela ajuda.

**Comment by pnmcosta** [comment]
Os rejeitados serão sempre enviados para o webservice, assim como aceites, deverá aí guardar a resposta da MB WAY ao pedido feito com o exemplo acima.

Note que esta API é meramente um canal/implementação de comunicação com os serviços MBWAY que, não invalida ter conhecimentos da integração conforme https://www.mbway.pt/developers/

**Comment by brunobola** [comment]
Sim eu tinha começado por implementar tudo de raiz, mas como me na sibs me indicaram o teu protejo comecei por usar para não ter que implementar tudo uma vez que já tinhas os WCFs criados e um cenário a funcionar.

Mas obrigado vou ver se consigo fazer dump do pedido deles para ver o que se passa.

**Comment by pnmcosta** [comment]
Se utiliza o service como o TestSite, em principio em ~/logs/ deverão estar os pedidos enviados, contudo já agora verifique se a pasta existe, e tem permissão da app_pool para modificar. Pode ser que seja isso que está a dar erro e não responda correctamente.

**Comment by brunobola** [comment]
Estive a ver os logs deles e parecem-me bem ou o log está a receber correctamente 020:
Assim de repente lembras-te de alguma coisa que tenha que fazer ao projeto TestSite que resolva ?
OU forçar o webservice a dar-me o estado do pedido

`<?xml version="1.0"?>
<requestFinancialOperationResult xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <amount>2000</amount>
  <currencyCode>9782</currencyCode>
  <merchantOperationID>57727757d95f3</merchantOperationID>
  <statusCode>020</statusCode>
  <timestamp>2016-06-28T14:11:00.71+01:00</timestamp>
  <token>bfeSNVmSaXBhxzBTJ6CdViHkEqQrKxQ9</token>
</requestFinancialOperationResult>`

**Comment by pnmcosta** [comment]
O webservice deverá responder do modo em que está implementado por defeito em nos metodos que faz override ao `MBWayAsyncServiceBase`.

O que faz com o que recebe no seu webservice e.g. `ProcessFinancialOperationResult` em https://github.com/pnmcosta/PMC.MBWay.Net/blob/master/PMC.MBWay.Net.TestSite/MBWayAsyncService.svc.cs#L43 é lógica que terá que desenvolver. Pode até pegar no XML e enviar para outro webservice, mas não é aconselhável por questões de segurança.

Se está a receber resposta é porque estará tudo em conformidade.

**Comment by brunobola** [comment]
Obrigado Pedro, 
entretanto vou desenvolver um verdadeiro mecanismo async usando o wait em .net.

**Comment by pnmcosta** [comment]
Boas, código e release actualizada, mais info em https://github.com/pnmcosta/PMC.MBWay.Net/releases/tag/v1.0.0-rc
